name: Test C++20 Compile
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo ./etc/DependencyInstaller.sh
      - name: Build OpenROAD
        run: |
          ./etc/Build.sh -compiler='clang-16' -cmake='-DCMAKE_CXX_STANDARD=20'
