name: Format Code with pre commit trigger
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:
      - name: setup
        run: |
          apt update 
          apt install -y clang clang-format clang-tidy
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
      - name: Check format of all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            clang-format --dry-run --Werror $file
          done
      - name: Check readability of all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            clang-tidy $file
          done
        
