name: Labelled Ready to Sync Public
on:
  pull_request:
    types: [labeled]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'The-OpenROAD-Project-private' && github.event.label.name == 'Ready To Sync Public'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
            ref: master
            token: ${{ secrets.GITHUBPUBLICREPOTOKEN }}
      - name: add remote
        run: git remote add staging https://github.com/The-OpenROAD-Project-staging/OpenROAD.git
      - name: print remotes
        run: git remote -v ; echo ${GITHUB_REF#refs/heads/}
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Status
        run: git status
      - name: Prints name of pull request base branch
        run: echo ${github.base_ref}

        
